[window]
decorations='None'

[font]
size = 11.0

[font.bold]
family = "Fira Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Fira Mono Nerd Font"
style = "Bold Italic"

[font.normal]
family = "Fira Mono Nerd Font"
style = "Regular"

